FROM node:16.20.0


RUN apt-get update -y
RUN apt-get install -y ffmpeg
RUN apt-get upgrade -y

WORKDIR /uazapi

COPY ./package.json .


ENV DOCKER_ENV=true

ENV CORS_ORIGIN='*' 
ENV CORS_METHODS='POST,GET,PUT,DELETE'
ENV CORS_CREDENTIALS=true

ENV LOG_LEVEL='ERROR,WARN,DEBUG,INFO,LOG,VERBOSE,DARK'
ENV LOG_COLOR=false

ENV DEL_INSTANCE=5

ENV STORE_CLEANING_INTERVAL=7200 
ENV STORE_MESSAGE=false
ENV STORE_CONTACTS=false
ENV STORE_CHATS=false

ENV DATABASE_ENABLED=false
ENV DATABASE_CONNECTION_URI='mongodb://<USER>:<PASSWORD>@<HOST>/?authSource=admin&readPreference=primary&ssl=false&directConnection=true'
ENV DATABASE_HOST: 127.0.0.1
ENV DATABASE_PORT: 26712
ENV DATABASE_USER: root
ENV DATABASE_PASSWORD: b5ti18bDi7NCENgiLctv
ENV DATABASE_CONNECTION_DB_PREFIX_NAME='uazapi'




# ENV DATABASE_SAVE_DATA_INSTANCE=false
# ENV DATABASE_SAVE_DATA_OLD_MESSAGE=false
# ENV DATABASE_SAVE_DATA_NEW_MESSAGE=true
# ENV DATABASE_SAVE_MESSAGE_UPDATE=true
# ENV DATABASE_SAVE_DATA_CONTACTS=true
# ENV DATABASE_SAVE_DATA_CHATS=true

ENV REDIS_ENABLED=false
ENV REDIS_URI='redis://<HOST>/1'
ENV REDIS_PREFIX_KEY='uazapi'

ENV WEBHOOK_GLOBAL_URL='<url>'
ENV WEBHOOK_GLOBAL_ENABLED=false

ENV WEBHOOK_EVENTS_STATUS_INSTANCE=true
ENV WEBHOOK_EVENTS_QRCODE_UPDATED=true
ENV WEBHOOK_EVENTS_MESSAGES_SET=true
ENV WEBHOOK_EVENTS_MESSAGES_UPDATE=true
ENV WEBHOOK_EVENTS_MESSAGES_UPSERT=true
ENV WEBHOOK_EVENTS_SEND_MESSAGE=true
ENV WEBHOOK_EVENTS_CONTACTS_SET=true
ENV WEBHOOK_EVENTS_CONTACTS_UPSERT=true
ENV WEBHOOK_EVENTS_CONTACTS_UPDATE=true
ENV WEBHOOK_EVENTS_PRESENCE_UPDATE=true
ENV WEBHOOK_EVENTS_CHATS_SET=true
ENV WEBHOOK_EVENTS_CHATS_UPSERT=true
ENV WEBHOOK_EVENTS_CHATS_UPDATE=true
ENV WEBHOOK_EVENTS_CONNECTION_UPDATE=true
ENV WEBHOOK_EVENTS_GROUPS_UPSERT=false
ENV WEBHOOK_EVENTS_GROUPS_UPDATE=false
ENV WEBHOOK_EVENTS_GROUP_PARTICIPANTS_UPDATE=false

ENV WEBHOOK_EVENTS_NEW_JWT_TOKEN=true

ENV CONFIG_SESSION_PHONE_CLIENT='uazapi'
ENV CONFIG_SESSION_PHONE_NAME='Chrome'

ENV QRCODE_LIMIT=6

ENV AUTHENTICATION_TYPE='apikey' 

ENV AUTHENTICATION_API_KEY='trocar_globalkey_uf9y3WXOK2nc9MJm1W6o82dS9fmbi0'

ENV AUTHENTICATION_JWT_EXPIRIN_IN=3600
ENV AUTHENTICATION_JWT_SECRET='L0YWtjb2w554WFqPG'

RUN npm install

COPY . .

CMD [ "node", "./uazapi.js" ]
