
version: '3.8'

networks:
  api-net:
    driver: bridge

services:
  mongodb:
    container_name: mongodb

    # This image already has a single replica set
    image: mongo

    restart: always
    volumes:
      # sudo mkdir -p /data/mongodb
      - /data/mongodb:/data/db
    ports:
      - 26712:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: b5ti18bDi7NCENgiLctv
    networks:
      - api-net
    expose:
      - 26712
